### ISSUE TITLE
Image Overwrite

### ISSUE THREAD

**Issue by l2ose** [Amenly/CyberDrop#3]
When picture in the gallery have same name the image got overwriten and seem to stuck in loop~

**Comment by Amenly** [comment]
I have a fix for it, I just need to test it. Unfortunately, the Cyberdrop website won't let me access my albums for some reason. Any chance you could share a link to an album with duplicate names?

**Comment by l2ose** [comment]
/a/0s9zwOta

**Comment by Amenly** [comment]
Released a new version; it should be fixed now but let me know if you encounter any issues.

**Comment by l2ose** [comment]
So It no longer loop indefinitely and download all the file without overwritten anything with same name.
Counter look nice but the number doesn't seem to increase and stuck at [0/total image no.] 
Also I try to test download second time from same album no overwritten file but increase copies so I guess it work now?

Further testing and this might be just my pc but sometime the script miss just one image and froze, other time not and perform perfectly.

Also you added "copy" into the middle of duplicate files name, so as not to overwritten or is it just my pc? 

Anyway thanks for speedy update, Have a good day dood~

**Comment by Amenly** [comment]
> Counter look nice but the number doesn't seem to increase and stuck at [0/total image no.]

I might have a fix for that. I ran the script on an album with 300 items and the counter stopped at ~220 despite downloading all 300 items.

> Further testing and this might be just my pc but sometime the script miss just one image and froze, other time not and perform perfectly.

When I was doing the tests with the 300-item album, sometimes I was downloading all 300 items and other times only 299. I believe it's on cyberdrop's end. I'm going to add some code to handle 400-level status codes and make it clear which files were unable to be downloaded.

> Also you added "copy" into the middle of duplicate files name, so as not to overwritten or is it just my pc?

And yes, I copied the way macOS handles duplicate files. They append ' copy' to the end of file names and for subsequent duplicates, they begin numbering the copies (e.g., ' copy 2', ' copy 3', ' copy 4', etc.). I may change this in the future for Windows and Linux users so that it feels more native to them (though I'll have to do some research to see how it looks on Linux and if it varies between distro)
